trigger:
  - master
  - Dev
  - QA

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseJavaVersion@1
    inputs:
      version: "16"

  - task: Gradle@2
    inputs:
      workingDirectory: 'C:\Users\romer\Documents\ITLA\6to Cuatrimestre\Electiva 2 (DevOps)\pro'
      tasks: "test"

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "**/build/test-results/**/*.xml"
      failTaskOnFailedTests: true
